# Generated by Django 6.0.4 on 2026-04-08 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_review_replied_at_review_seller_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
