# Generated by Django 6.0.4 on 2026-04-10 03:51

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_confirmed',
            field=models.BooleanField(default=False, verbose_name='Xaridor tasdiqladi'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Karta'), ('cash', 'Naqd')], default='card', max_length=10, verbose_name="To'lov turi"),
        ),
        migrations.AddField(
            model_name='order',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Jarima summasi'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='Top mahsulot'),
        ),
        migrations.AddField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('active', 'Faol'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holati'),
        ),
        migrations.AddField(
            model_name='user',
            name='stir_pinfl',
            field=models.CharField(blank=True, max_length=14, verbose_name='STIR/PINFL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.PathAndRename('products/'), verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.PathAndRename('store_logos/'), verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.PathAndRename('avatars/'), verbose_name='Rasm'),
        ),
    ]
