# Generated by Django 6.0.4 on 2026-04-10 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_brand_region_product_brand_store_delivery_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores_at', to='main.region', verbose_name="Do'kon joylashuvi"),
        ),
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('active', 'Faol'), ('rejected', 'Rad etildi'), ('suspended', "Vaqtinchalik to'xtatilgan")], default='pending', max_length=20, verbose_name='Holati'),
        ),
    ]
