# Generated by Django 6.0.4 on 2026-04-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_store_region_alter_store_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='buyer_confirmed',
            field=models.BooleanField(default=False, verbose_name='Xaridor tasdiqladi'),
        ),
    ]
